channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - abseil-cpp
  - adal
  - adlfs
  - affine
  - aiobotocore
  - aiodns
  - aiohttp
  - aiohttp-client-cache
  - aioitertools
  - aioredis
  - aiosignal
  - aiosqlite
  - alabaster
  - alembic
  - alsa-lib
  - ansiwrap
  - anyio
  - aom
  - appdirs
  - argon2-cffi
  - argon2-cffi-bindings
  - arrow-cpp
  - asciitree
  - asttokens
  - async-timeout
  - async_generator
  - async_retriever
  - atk-1.0
  - attrs
  - aws-c-cal
  - aws-c-common
  - aws-c-event-stream
  - aws-c-io
  - aws-checksums
  - aws-sdk-cpp
  - awscli
  - azure-core
  - azure-datalake-store
  - azure-identity
  - azure-storage-blob
  - babel
  - backcall
  - backoff
  - backports
  - backports.functools_lru_cache
  - beautifulsoup4
  - bias_correction
  - birdy
  - black
  - bleach
  - blinker
  - blosc
  - bokeh
  - bokeh-root-cmd
  - boltons
  - boost-cpp
  - boto3
  - botocore
  - bottleneck
  - bounded-pool-executor
  - bqplot
  - branca
  - brotli
  - brotli-bin
  - brotlipy
  - brunsli
  - bzip2
  - c-ares
  - c-blosc2
  - ca-certificates
  - cached-property
  - cached_property
  - cairo
  - cartopy
  - cattrs
  - cchardet
  - cdsdashboards
  - cdsdashboards-singleuser
  - certifi
  - certipy
  - cf_xarray
  - cffi
  - cfgrib
  - cfitsio
  - cftime
  - charls
  - charset-normalizer
  - click-plugins
  - cligj
  - climpred
  - cloudpickle
  - coiled
  - colorama
  - colorcet
  - colour
  - commonmark
  - conda
  - conda-package-handling
  - configurable-http-proxy
  - cramjam
  - cryptography
  - csa
  - curl
  - cycler
  - cytoolz
  - dask-gateway
  - dask-geopandas
  - dask-image
  - dataclasses
  - datacube
  - datashader
  - datashape
  - dav1d
  - dbus
  - debugpy
  - decorator
  - defusedxml
  - depfinder
  - distributed
  - docrep
  - docutils
  - double-conversion
  - draco
  - earthdata
  - eccodes
  - eigen
  - entrypoints
  - entwine
  - eofs
  - erddapy
  - esmf
  - esmpy
  - et_xmlfile
  - executing
  - expat
  - fasteners
  - fastparquet
  - ffmpeg
  - fftw
  - filelock
  - findlibs
  - fiona
  - flit-core
  - folium
  - font-ttf-dejavu-sans-mono
  - font-ttf-inconsolata
  - font-ttf-source-code-pro
  - font-ttf-ubuntu
  - fontconfig
  - fonts-conda-ecosystem
  - fonts-conda-forge
  - freeglut
  - freetype
  - freexl
  - fribidi
  - frozenlist
  - fsspec
  - ftfy
  - funcsigs
  - future
  - g2clib
  - gcsfs
  - gdal
  - gdk-pixbuf
  - gdown
  - geogif
  - geographiclib
  - geojson
  - geolinks
  - geopy
  - geos
  - geotiff
  - geoviews
  - geoviews-core
  - gettext
  - gflags
  - giflib
  - gl2ps
  - glew
  - glib
  - glib-tools
  - glog
  - gmp
  - gnutls
  - google-api-core
  - google-auth-oauthlib
  - google-cloud-core
  - google-cloud-storage
  - google-crc32c
  - google-resumable-media
  - googleapis-common-protos
  - graphite2
  - graphviz
  - greenlet
  - gridgen
  - gridutils
  - grpc-cpp
  - grpcio
  - gst-plugins-base
  - gstreamer
  - gtk2
  - gts
  - h5netcdf
  - h5py
  - harfbuzz
  - hdf4
  - hdf5
  - heapdict
  - hologridgen
  - holoviews
  - htop
  - hvplot
  - icu
  - idna
  - imagecodecs
  - imageio
  - imagesize
  - importlib-metadata
  - importlib_metadata
  - importlib_resources
  - intake
  - intake-geopandas
  - intake-stac
  - intake-xarray
  - ipyevents
  - ipyfilechooser
  - ipykernel
  - ipyleaflet
  - ipysheet
  - ipyspin
  - ipython
  - ipython_genutils
  - ipytree
  - ipyurl
  - ipywidgets
  - isodate
  - isort
  - itsdangerous
  - jack
  - jasper
  - jedi
  - jhsingle-native-proxy
  - jinja2
  - jmespath
  - joblib
  - jpeg
  - jq
  - json-c
  - json5
  - jsoncpp
  - jsondiff
  - jsonpickle
  - jsonschema
  - jupyter-panel-proxy
  - jupyter-server-proxy
  - jupyter_bokeh
  - jupyter_client
  - jupyter_core
  - jupyter_server
  - jupyter_telemetry
  - jupyterhub
  - jupyterhub-base
  - jupyterlab
  - jupyterlab_code_formatter
  - jupyterlab_pygments
  - jupyterlab_server
  - jupyterlab_widgets
  - jupytext
  - jxrlib
  - kealib
  - keyutils
  - kiwisolver
  - krb5
  - lame
  - lark-parser
  - lcms2
  - ld_impl_linux-64
  - leafmap
  - lerc
  - libaec
  - libarchive
  - libavif
  - libblas
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcap
  - libcblas
  - libclang
  - libclang13
  - libcrc32c
  - libcups
  - libcurl
  - libdap4
  - libdb
  - libdeflate
  - libdrm
  - libedit
  - libev
  - libevent
  - libffi
  - libflac
  - libgcc-ng
  - libgd
  - libgdal
  - libgfortran-ng
  - libgfortran5
  - libglib
  - libglu
  - libgomp
  - libgoogle-cloud
  - libiconv
  - libidn2
  - libkml
  - liblapack
  - libllvm11
  - libllvm14
  - libmamba
  - libmambapy
  - libnetcdf
  - libnghttp2
  - libnl
  - libnsl
  - libogg
  - libopenblas
  - libopus
  - libpciaccess
  - libpng
  - libpq
  - libprotobuf
  - librsvg
  - librttopo
  - libsndfile
  - libsodium
  - libsolv
  - libspatialindex
  - libspatialite
  - libssh2
  - libstdcxx-ng
  - libtasn1
  - libtheora
  - libthrift
  - libtiff
  - libtool
  - libudev1
  - libunistring
  - libutf8proc
  - libuuid
  - libuv
  - libva
  - libvorbis
  - libvpx
  - libwebp
  - libwebp-base
  - libxcb
  - libxkbcommon
  - libxml2
  - libxslt
  - libzip
  - libzlib
  - libzopfli
  - llvmlite
  - locket
  - loguru
  - lxml
  - lz4
  - lz4-c
  - lzo
  - mailchecker
  - mako
  - mamba
  - mapclassify
  - markdown
  - markdown-it-py
  - markupsafe
  - matplotlib-base
  - matplotlib-inline
  - mdit-py-plugins
  - mdurl
  - mercantile
  - metpy
  - mistune
  - morecantile
  - mpi
  - mpi4py
  - mpich
  - msal
  - msal_extensions
  - msgpack-python
  - msrest
  - multidict
  - multipledispatch
  - munch
  - mypy_extensions
  - mysql-common
  - mysql-connector-c
  - mysql-libs
  - nbclassic
  - nbclient
  - nbconvert
  - nbconvert-core
  - nbconvert-pandoc
  - nbformat
  - nbgitpuller
  - nbstripout
  - nc-time-axis
  - ncurses
  - nest-asyncio
  - netcdf-fortran
  - netcdf4
  - nettle
  - networkx
  - nitro
  - nn
  - nodejs
  - noise
  - nomkl
  - notebook
  - notebook-shim
  - nspr
  - nss
  - numba
  - numcodecs
  - numexpr
  - numpy
  - oauthlib
  - odc-algo
  - odc-geo
  - odc-stac
  - oniguruma
  - openh264
  - openjpeg
  - openpyxl
  - openssl
  - orc
  - osmnx
  - owslib
  - p11-kit
  - packaging
  - pamela
  - pandas
  - pandoc
  - pandocfilters
  - panel
  - pangeo-forge-recipes
  - pango
  - papermill
  - param
  - parquet-cpp
  - parso
  - partd
  - pathspec
  - patsy
  - pcre
  - pdal
  - perl
  - pexpect
  - phonenumbers
  - pickleshare
  - pillow
  - pims
  - pint
  - pint-xarray
  - pip
  - pixman
  - planetary-computer
  - platformdirs
  - plotlydash-tornado-cmd
  - pluggy
  - pooch
  - poppler
  - poppler-data
  - portalocker
  - portaudio
  - postgresql
  - pqdm
  - proj
  - prometheus_client
  - prompt-toolkit
  - properscoring
  - proplot
  - protobuf
  - pscript
  - psutil
  - psycopg2
  - pthread-stubs
  - ptyprocess
  - pugixml
  - pulseaudio
  - pure_eval
  - py3dep
  - pyarrow
  - pyasn1
  - pyasn1-modules
  - pybind11-abi
  - pycares
  - pycosat
  - pycparser
  - pycrs
  - pyct
  - pyct-core
  - pycurl
  - pydantic
  - pydaymet
  - pyepsg
  - pygeohydro
  - pygeoogc
  - pygeos
  - pygeoutils
  - pygments
  - pygridgen
  - pyjwt
  - pynhd
  - pyopenssl
  - pyparsing
  - pyproj
  - pyrsistent
  - pyshp
  - pysocks
  - pystac
  - pystac-client
  - pytables
  - python
  - python-benedict
  - python-box
  - python-cmr
  - python-eccodes
  - python-fastjsonschema
  - python-forge
  - python-fsutil
  - python-gist
  - python-gnupg
  - python-graphviz
  - python-json-logger
  - python-slugify
  - python-snappy
  - python_abi
  - pytz
  - pyu2f
  - pyvista
  - pyviz_comms
  - pywavelets
  - pyyaml
  - pyzmq
  - qhub-dask
  - qt-main
  - rasterio
  - re2
  - readline
  - rechunker
  - reproc
  - reproc-cpp
  - requests
  - requests-cache
  - requests-oauthlib
  - retrying
  - rich
  - rio-cogeo
  - rioxarray
  - rsa
  - rshiny-server-cmd
  - rtree
  - ruamel.yaml
  - ruamel.yaml.clib
  - ruamel_yaml
  - s2n
  - s3fs
  - s3transfer
  - sat-search
  - sat-stac
  - scikit-image
  - scikit-learn
  - scipy
  - scooby
  - seawater
  - send2trash
  - setuptools
  - shapely
  - simpervisor
  - siphon
  - six
  - slicerator
  - snappy
  - sniffio
  - snowballstemmer
  - snuggs
  - sortedcontainers
  - soupsieve
  - sparse
  - spatialpandas
  - sphinx
  - sphinxcontrib-applehelp
  - sphinxcontrib-devhelp
  - sphinxcontrib-htmlhelp
  - sphinxcontrib-jsmath
  - sphinxcontrib-qthelp
  - sphinxcontrib-serializinghtml
  - sqlalchemy
  - sqlite
  - stack_data
  - stackstac
  - statsmodels
  - stdlib-list
  - svt-av1
  - tbb
  - tbb-devel
  - tblib
  - tenacity
  - terminado
  - text-unidecode
  - textual
  - textwrap3
  - threadpoolctl
  - tifffile
  - tiledb
  - tinycss2
  - tk
  - toml
  - tomli
  - toolz
  - tornado
  - tqdm
  - traitlets
  - traittypes
  - typed-ast
  - typing-extensions
  - typing_extensions
  - tzcode
  - tzdata
  - ujson
  - unidecode
  - unzip
  - url-normalize
  - urllib3
  - utfcpp
  - utide
  - vim
  - vtk
  - wcwidth
  - webencodings
  - websocket-client
  - wgrib2
  - wheel
  - whitebox
  - whiteboxgui
  - widgetsnbextension
  - wrapt
  - x264
  - x265
  - xagg
  - xarray
  - xarray-spatial
  - xarray_leaflet
  - xcb-util
  - xcb-util-image
  - xcb-util-keysyms
  - xcb-util-renderutil
  - xcb-util-wm
  - xclim
  - xerces-c
  - xesmf
  - xhistogram
  - xmltodict
  - xoak
  - xorg-fixesproto
  - xorg-inputproto
  - xorg-kbproto
  - xorg-libice
  - xorg-libsm
  - xorg-libx11
  - xorg-libxau
  - xorg-libxdmcp
  - xorg-libxext
  - xorg-libxfixes
  - xorg-libxi
  - xorg-libxrender
  - xorg-libxt
  - xorg-renderproto
  - xorg-xextproto
  - xorg-xproto
  - xrft
  - xrviz
  - xskillscore
  - xyzservices
  - xz
  - yaml
  - yaml-cpp
  - yarl
  - zarr
  - zeromq
  - zfp
  - zict
  - zip
  - zipp
  - zlib
  - zlib-ng
  - zstandard
  - zstd
  - pip:
    - attr
    - cachetools
    - click
    - dask
    - docopt
    - flask
    - future-annotations
    - gdptools
    - geopandas
    - google-api-python-client
    - google-auth
    - google-auth-httplib2
    - h11
    - h5pyd
    - httpcore
    - httplib2
    - httpx
    - kbatch
    - kubernetes
    - msrestazure
    - noaa-coops
    - pydap
    - pygeoapi
    - python-dateutil
    - rasterstats
    - requests-file
    - requests-toolbelt
    - requests-unixsocket
    - rfc3986
    - simplejson
    - tinydb
    - tokenize-rt
    - unicodecsv
    - uritemplate
    - webob
    - werkzeug
    - xstac
    - zeep
    - git+https://github.com/fsspec/kerchunk.git
