channels:
- conda-forge
dependencies:
- python=3.9
- adlfs
- aiobotocore
- awscli
- birdy
- black
- bokeh
- boto3
- cf_xarray
- cfgrib
- climpred
- curl>7.79.0
- datashader
- datacube
- dask-geopandas
- depfinder
- distributed
- earthdata
- entwine
- erddapy
- fastparquet
- folium
- fsspec
- gcsfs
- geolinks
- geopy
- geoviews>1.9.0
- graphviz
- h5netcdf
- h5py
- hologridgen
- holoviews
- htop
- hvplot
- imagecodecs
- intake
- intake-geopandas
- intake-stac
- intake-xarray
- ipykernel
- ipywidgets
- isort
- jinja2
- jupyter_bokeh
- jupyter-panel-proxy
- jupyterlab_code_formatter
- jupytext
- jq
- leafmap
- lxml
- lz4
- mamba
- metpy
- nbgitpuller
- nbstripout
- numba
- numcodecs
- odc-algo
- odc-stac
- openpyxl
- osmnx
- owslib
- pandas
- panel
- papermill
- param
- pip
- pint-xarray
- planetary-computer
- pyarrow
- pyepsg
- pygeohydro>0.13.0
- pydaymet
- pynhd
- py3dep
- pygeoogc
- pygeoutils
- pyvista
- async_retriever
- pystac
- pystac-client
- python-graphviz
- python-snappy
- pyyaml
- python-gist
- qhub-dask ==0.4.3
- rechunker
- requests
- rich
- rio-cogeo
- s3fs
- sat-search
- sat-stac
- scikit-image
- seawater
- siphon
- spatialpandas
- stackstac
- toolz
- ujson
- unzip
- utide
- vim
- wgrib2
- xagg
- xarray-spatial
- xclim
- xesmf
- xoak
- xrviz
- xskillscore
- zarr
- zip
- zstandard
- cdsdashboards-singleuser>=0.5.6
- pip:
  - noaa-coops
  - kbatch
  - git+https://github.com/fsspec/kerchunk.git
