channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - abseil-cpp=20210324.2
  - adal=1.2.7
  - adlfs=2022.7.0
  - affine=2.3.1
  - aiobotocore=2.3.4
  - aiodns=3.0.0
  - aiohttp=3.8.1
  - aiohttp-client-cache=0.7.2
  - aioitertools=0.10.0
  - aioredis=2.0.1
  - aiosignal=1.2.0
  - aiosqlite=0.17.0
  - alabaster=0.7.12
  - alembic=1.8.1
  - alsa-lib=1.2.6.1
  - ansiwrap=0.8.4
  - anyio=3.6.1
  - aom=3.4.0
  - appdirs=1.4.4
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arrow-cpp=8.0.0
  - asciitree=0.3.3
  - asttokens=2.0.5
  - async-timeout=4.0.2
  - async_generator=1.10
  - async_retriever=0.3.3
  - atk-1.0=2.36.0
  - attrs=21.4.0
  - aws-c-cal=0.5.11
  - aws-c-common=0.6.2
  - aws-c-event-stream=0.2.7
  - aws-c-io=0.10.5
  - aws-checksums=0.1.11
  - aws-sdk-cpp=1.8.186
  - awscli=1.22.76
  - azure-core=1.24.2
  - azure-datalake-store=0.0.51
  - azure-identity=1.10.0
  - azure-storage-blob=12.13.0
  - babel=2.10.3
  - backcall=0.2.0
  - backoff=1.11.1
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.11.1
  - bias_correction=0.4
  - birdy=v0.6.9
  - black=22.6.0
  - bleach=5.0.1
  - blinker=1.4
  - blosc=1.21.1
  - bokeh=2.4.3
  - bokeh-root-cmd=0.1.2
  - boltons=21.0.0
  - boost-cpp=1.74.0
  - boto3=1.21.21
  - botocore=1.24.21
  - bottleneck=1.3.5
  - bounded-pool-executor=0.0.3
  - bqplot=0.12.33
  - branca=0.5.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.18.1
  - c-blosc2=2.2.0
  - ca-certificates=2022.6.15
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.16.0
  - cartopy=0.20.3
  - cattrs=1.10.0
  - cchardet=2.1.7
  - cdsdashboards=0.6.2
  - cdsdashboards-singleuser=0.6.2
  - certifi=2022.6.15
  - certipy=0.1.3
  - cf_xarray=0.7.4
  - cffi=1.15.1
  - cfgrib=0.9.10.1
  - cfitsio=4.1.0
  - cftime=1.6.1
  - charls=2.3.4
  - charset-normalizer=2.1.0
  - click-plugins=1.1.1
  - cligj=0.7.2
  - climpred=2.2.0
  - cloudpickle=2.1.0
  - coiled=0.2.15
  - colorama=0.4.3
  - colorcet=3.0.0
  - colour=0.1.5
  - commonmark=0.9.1
  - conda=4.13.0
  - conda-package-handling=1.8.1
  - configurable-http-proxy=4.5.1
  - cramjam=2.5.0
  - cryptography=37.0.4
  - csa=1.22.0
  - curl=7.83.1
  - cycler=0.11.0
  - cytoolz=0.12.0
  - dask-gateway=2022.4.0
  - dask-geopandas=0.2.0
  - dask-image=2021.12.0
  - dataclasses=0.8
  - datacube=1.8.7
  - datashader=0.14.1
  - datashape=0.5.4
  - dav1d=1.0.0
  - dbus=1.13.6
  - debugpy=1.6.0
  - decorator=5.1.1
  - defusedxml=0.7.1
  - depfinder=2.8.1
  - distributed=2022.4.2
  - docrep=0.3.2
  - docutils=0.15.2
  - double-conversion=3.2.0
  - draco=1.5.3
  - earthdata=0.2.2
  - eccodes=2.26.0
  - eigen=3.4.0
  - entrypoints=0.4
  - entwine=2.2.0
  - eofs=1.4.0
  - erddapy=1.2.1
  - esmf=8.2.0
  - esmpy=8.2.0
  - et_xmlfile=1.0.1
  - executing=0.9.0
  - expat=2.4.8
  - fasteners=0.17.3
  - fastparquet=0.8.1
  - ffmpeg=4.4.2
  - fftw=3.3.10
  - filelock=3.7.1
  - findlibs=0.0.2
  - fiona=1.8.21
  - flit-core=3.7.1
  - folium=0.12.1.post1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freeglut=3.2.2
  - freetype=2.10.4
  - freexl=1.0.6
  - fribidi=1.0.10
  - frozenlist=1.3.0
  - fsspec=2022.5.0
  - ftfy=6.1.1
  - funcsigs=1.0.2
  - future=0.18.2
  - g2clib=1.6.3
  - gcsfs=2022.5.0
  - gdal=3.5.0
  - gdk-pixbuf=2.42.8
  - gdown=4.5.1
  - geogif=0.1.3
  - geographiclib=1.52
  - geojson=2.5.0
  - geolinks=0.2.0
  - geopy=2.2.0
  - geos=3.10.3
  - geotiff=1.7.1
  - geoviews=1.9.5
  - geoviews-core=1.9.5
  - gettext=0.19.8.1
  - gflags=2.2.2
  - giflib=5.2.1
  - gl2ps=1.4.2
  - glew=2.1.0
  - glib=2.72.1
  - glib-tools=2.72.1
  - glog=0.6.0
  - gmp=6.2.1
  - gnutls=3.7.6
  - google-api-core=2.8.2
  - google-auth-oauthlib=0.5.2
  - google-cloud-core=2.3.2
  - google-cloud-storage=2.4.0
  - google-crc32c=1.1.2
  - google-resumable-media=2.3.3
  - googleapis-common-protos=1.56.4
  - graphite2=1.3.13
  - graphviz=5.0.0
  - greenlet=1.1.2
  - gridgen=1.51.5
  - gridutils=1.0
  - grpc-cpp=1.45.2
  - grpcio=1.46.3
  - gst-plugins-base=1.20.3
  - gstreamer=1.20.3
  - gtk2=2.24.33
  - gts=0.7.6
  - h5netcdf=1.0.1
  - h5py=3.7.0
  - harfbuzz=4.4.1
  - hdf4=4.2.15
  - hdf5=1.12.1
  - heapdict=1.0.1
  - hologridgen=1.0.2
  - holoviews=1.15.0
  - htop=3.2.1
  - hvplot=0.8.0
  - icu=70.1
  - idna=3.3
  - imagecodecs=2022.2.22
  - imageio=2.19.3
  - imagesize=1.4.1
  - importlib-metadata=4.11.4
  - importlib_metadata=4.11.4
  - importlib_resources=5.9.0
  - intake=0.6.5
  - intake-geopandas=0.4.0
  - intake-stac=0.4.0
  - intake-xarray=0.6.0
  - ipyevents=2.0.1
  - ipyfilechooser=0.6.0
  - ipykernel=6.15.1
  - ipyleaflet=0.17.0
  - ipysheet=0.5.0
  - ipyspin=0.1.5
  - ipython=8.4.0
  - ipython_genutils=0.2.0
  - ipytree=0.2.1
  - ipyurl=0.1.2
  - ipywidgets=7.7.1
  - isodate=0.6.1
  - isort=5.10.1
  - itsdangerous=2.1.2
  - jack=1.9.18
  - jasper=2.0.33
  - jedi=0.18.1
  - jhsingle-native-proxy=0.8.0
  - jinja2=3.1.2
  - jmespath=1.0.1
  - joblib=1.1.0
  - jpeg=9e
  - jq=1.6
  - json-c=0.16
  - json5=0.9.5
  - jsoncpp=1.9.5
  - jsondiff=2.0.0
  - jsonpickle=2.2.0
  - jsonschema=4.7.2
  - jupyter-panel-proxy=0.1.0
  - jupyter-server-proxy=3.2.1
  - jupyter_bokeh=3.0.4
  - jupyter_client=7.2.2
  - jupyter_core=4.11.1
  - jupyter_server=1.18.1
  - jupyter_telemetry=0.1.0
  - jupyterhub=2.3.1
  - jupyterhub-base=2.3.1
  - jupyterlab=3.4.4
  - jupyterlab_code_formatter=1.5.1
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.15.0
  - jupyterlab_widgets=1.1.1
  - jupytext=1.14.0
  - jxrlib=1.1
  - kealib=1.4.15
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.19.3
  - lame=3.100
  - lark-parser=0.12.0
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - leafmap=0.10.3
  - lerc=3.0
  - libaec=1.0.6
  - libarchive=3.5.2
  - libavif=0.10.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcap=2.64
  - libcblas=3.9.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcrc32c=1.1.2
  - libcups=2.3.3
  - libcurl=7.83.1
  - libdap4=3.20.6
  - libdb=6.2.32
  - libdeflate=1.12
  - libdrm=2.4.112
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.2
  - libflac=1.3.4
  - libgcc-ng=12.1.0
  - libgd=2.3.3
  - libgdal=3.5.0
  - libgfortran-ng=12.1.0
  - libgfortran5=12.1.0
  - libglib=2.72.1
  - libglu=9.0.0
  - libgomp=12.1.0
  - libgoogle-cloud=1.40.2
  - libiconv=1.16
  - libidn2=2.3.3
  - libkml=1.3.0
  - liblapack=3.9.0
  - libllvm11=11.1.0
  - libllvm14=14.0.6
  - libmamba=0.24.0
  - libmambapy=0.24.0
  - libnetcdf=4.8.1
  - libnghttp2=1.47.0
  - libnl=3.7.0
  - libnsl=2.0.0
  - libogg=1.3.4
  - libopenblas=0.3.20
  - libopus=1.3.1
  - libpciaccess=0.16
  - libpng=1.6.37
  - libpq=14.4
  - libprotobuf=3.20.1
  - librsvg=2.54.4
  - librttopo=1.1.0
  - libsndfile=1.0.31
  - libsodium=1.0.18
  - libsolv=0.7.22
  - libspatialindex=1.9.3
  - libspatialite=5.0.1
  - libssh2=1.10.0
  - libstdcxx-ng=12.1.0
  - libtasn1=4.18.0
  - libtheora=1.1.1
  - libthrift=0.16.0
  - libtiff=4.4.0
  - libtool=2.4.6
  - libudev1=249
  - libunistring=0.9.10
  - libutf8proc=2.7.0
  - libuuid=2.32.1
  - libuv=1.43.0
  - libva=2.15.0
  - libvorbis=1.3.7
  - libvpx=1.11.0
  - libwebp=1.2.3
  - libwebp-base=1.2.3
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.9.14
  - libxslt=1.1.35
  - libzip=1.9.2
  - libzlib=1.2.12
  - libzopfli=1.0.3
  - llvmlite=0.38.1
  - locket=1.0.0
  - loguru=0.6.0
  - lxml=4.9.1
  - lz4=4.0.0
  - lz4-c=1.9.3
  - lzo=2.10
  - mailchecker=4.1.18
  - mako=1.2.1
  - mamba=0.24.0
  - mapclassify=2.4.3
  - markdown=3.4.1
  - markdown-it-py=2.1.0
  - markupsafe=2.1.1
  - matplotlib-base=3.4.3
  - matplotlib-inline=0.1.3
  - mdit-py-plugins=0.3.0
  - mdurl=0.1.0
  - mercantile=1.2.1
  - metpy=1.3.1
  - mistune=0.8.4
  - morecantile=3.1.2
  - mpi=1.0
  - mpi4py=3.1.3
  - mpich=4.0.2
  - msal=1.17.0
  - msal_extensions=1.0.0
  - msgpack-python=1.0.4
  - msrest=0.6.21
  - multidict=6.0.2
  - multipledispatch=0.6.0
  - munch=2.5.0
  - mypy_extensions=0.4.3
  - mysql-common=8.0.29
  - mysql-connector-c=6.1.11
  - mysql-libs=8.0.29
  - nbclassic=0.4.3
  - nbclient=0.6.6
  - nbconvert=6.5.0
  - nbconvert-core=6.5.0
  - nbconvert-pandoc=6.5.0
  - nbformat=5.4.0
  - nbgitpuller=1.1.0
  - nbstripout=0.5.0
  - nc-time-axis=1.4.1
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - netcdf-fortran=4.5.4
  - netcdf4=1.6.0
  - nettle=3.8
  - networkx=2.8.5
  - nitro=2.7.dev6
  - nn=1.86.0
  - nodejs=17.9.0
  - noise=1.2.2
  - nomkl=1.0
  - notebook=6.4.12
  - notebook-shim=0.1.0
  - nspr=4.32
  - nss=3.78
  - numba=0.55.2
  - numcodecs=0.10.0
  - numexpr=2.8.3
  - numpy=1.22.4
  - oauthlib=3.2.0
  - odc-algo=0.2.2
  - odc-geo=0.2.1
  - odc-stac=0.3.1
  - oniguruma=6.9.8
  - openh264=2.2.0
  - openjpeg=2.4.0
  - openpyxl=3.0.9
  - openssl=1.1.1q
  - orc=1.7.5
  - osmnx=1.2.1
  - owslib=0.25.0
  - p11-kit=0.24.1
  - packaging=21.3
  - pamela=1.0.0
  - pandas=1.4.2
  - pandoc=2.18
  - pandocfilters=1.5.0
  - panel=0.13.1
  - pangeo-forge-recipes=0.9.0
  - pango=1.50.8
  - papermill=2.3.4
  - param=1.12.2
  - parquet-cpp=1.5.1
  - parso=0.8.3
  - partd=1.2.0
  - pathspec=0.9.0
  - patsy=0.5.2
  - pcre=8.45
  - pdal=2.4.2
  - perl=5.32.1
  - pexpect=4.8.0
  - phonenumbers=8.12.52
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pims=0.6.1
  - pint=0.19.2
  - pint-xarray=0.2.1
  - pip=22.2
  - pixman=0.40.0
  - planetary-computer=0.4.6
  - platformdirs=2.5.2
  - plotlydash-tornado-cmd=0.0.6
  - pluggy=1.0.0
  - pooch=1.6.0
  - poppler=22.04.0
  - poppler-data=0.4.11
  - portalocker=2.5.1
  - portaudio=19.6.0
  - postgresql=14.4
  - pqdm=0.1.0
  - proj=9.0.1
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.30
  - properscoring=0.1
  - proplot=0.9.5
  - protobuf=3.20.1
  - pscript=0.7.5
  - psutil=5.9.1
  - psycopg2=2.9.3
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pugixml=1.11.4
  - pulseaudio=14.0
  - pure_eval=0.2.2
  - py3dep=0.13.3
  - pyarrow=8.0.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pybind11-abi=4
  - pycares=4.0.0
  - pycosat=0.6.3
  - pycparser=2.21
  - pycrs=1.0.2
  - pyct=0.4.6
  - pyct-core=0.4.6
  - pycurl=7.45.1
  - pydantic=1.9.1
  - pydaymet=0.13.2
  - pyepsg=0.4.0
  - pygeohydro=0.13.2
  - pygeoogc=0.13.2
  - pygeos=0.12.0
  - pygeoutils=0.13.2
  - pygments=2.12.0
  - pygridgen=0.2.1
  - pyjwt=2.4.0
  - pynhd=0.13.2
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyproj=3.3.1
  - pyrsistent=0.18.1
  - pyshp=2.3.0
  - pysocks=1.7.1
  - pystac=1.6.0
  - pystac-client=0.4.0
  - pytables=3.7.0
  - python=3.9.13
  - python-benedict=0.24.3
  - python-box=6.0.2
  - python-cmr=0.4.1
  - python-eccodes=1.4.2
  - python-fastjsonschema=2.16.1
  - python-forge=18.6.0
  - python-fsutil=0.6.1
  - python-gist=0.10.6
  - python-gnupg=0.4.9
  - python-graphviz=0.20.1
  - python-json-logger=2.0.1
  - python-slugify=6.1.2
  - python-snappy=0.6.0
  - python_abi=3.9
  - pytz=2022.1
  - pyu2f=0.1.5
  - pyvista=0.35.2
  - pyviz_comms=2.2.0
  - pywavelets=1.3.0
  - pyyaml=5.4.1
  - pyzmq=23.2.0
  - qhub-dask=0.4.3
  - qt-main=5.15.4
  - rasterio=1.3.0
  - re2=2022.06.01
  - readline=8.1.2
  - rechunker=0.5.0
  - reproc=14.2.3
  - reproc-cpp=14.2.3
  - requests=2.28.1
  - requests-cache=0.9.4
  - requests-oauthlib=1.3.1
  - retrying=1.3.3
  - rich=12.5.1
  - rio-cogeo=3.3.0
  - rioxarray=0.11.1
  - rsa=4.7.2
  - rshiny-server-cmd=0.0.2
  - rtree=1.0.0
  - ruamel.yaml=0.17.21
  - ruamel.yaml.clib=0.2.6
  - ruamel_yaml=0.15.80
  - s2n=1.0.10
  - s3fs=2022.5.0
  - s3transfer=0.5.2
  - sat-search=0.3.0
  - sat-stac=0.4.1
  - scikit-image=0.19.3
  - scikit-learn=1.1.1
  - scipy=1.8.1
  - scooby=0.6.0
  - seawater=3.3.4
  - send2trash=1.8.0
  - setuptools=63.2.0
  - shapely=1.8.2
  - simpervisor=0.4
  - siphon=0.9
  - six=1.16.0
  - slicerator=1.1.0
  - snappy=1.1.9
  - sniffio=1.2.0
  - snowballstemmer=2.2.0
  - snuggs=1.4.7
  - sortedcontainers=2.4.0
  - soupsieve=2.3.2.post1
  - sparse=0.13.0
  - spatialpandas=0.4.3
  - sphinx=5.0.2
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.5
  - sqlalchemy=1.4.39
  - sqlite=3.39.2
  - stack_data=0.3.0
  - stackstac=0.4.2
  - statsmodels=0.13.2
  - stdlib-list=0.7.0
  - svt-av1=1.1.0
  - tbb=2021.5.0
  - tbb-devel=2021.5.0
  - tblib=1.7.0
  - tenacity=8.0.1
  - terminado=0.15.0
  - text-unidecode=1.3
  - textual=0.1.18
  - textwrap3=0.9.2
  - threadpoolctl=3.1.0
  - tifffile=2022.5.4
  - tiledb=2.9.5
  - tinycss2=1.1.1
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - toolz=0.12.0
  - tornado=6.2
  - tqdm=4.64.0
  - traitlets=5.3.0
  - traittypes=0.2.1
  - typed-ast=1.5.4
  - typing-extensions=4.3.0
  - typing_extensions=4.3.0
  - tzcode=2022a
  - tzdata=2022a
  - ujson=5.3.0
  - unidecode=1.3.4
  - unzip=6.0
  - url-normalize=1.4.3
  - urllib3=1.26.10
  - utfcpp=3.2.1
  - utide=0.3.0
  - vim=8.2.4950
  - vtk=9.1.0
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.3.3
  - wgrib2=3.1.1
  - wheel=0.37.1
  - whitebox=2.1.3
  - whiteboxgui=0.7.0
  - widgetsnbextension=3.6.1
  - wrapt=1.14.1
  - x264=1!161.3030
  - x265=3.5
  - xagg=0.3.0.2
  - xarray=2022.6.0
  - xarray-spatial=0.3.5
  - xarray_leaflet=0.1.15
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xclim=0.36.0
  - xerces-c=3.2.3
  - xesmf=0.6.3
  - xhistogram=0.3.1
  - xmltodict=0.13.0
  - xoak=0.1.1
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.2.1
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xrft=1.0.0
  - xrviz=0.1.4
  - xskillscore=0.0.24
  - xyzservices=2022.6.0
  - xz=5.2.5
  - yaml=0.2.5
  - yaml-cpp=0.7.0
  - yarl=1.7.2
  - zarr=2.12.0
  - zeromq=4.3.4
  - zfp=0.5.5
  - zict=2.2.0
  - zip=3.0
  - zipp=3.8.0
  - zlib=1.2.12
  - zlib-ng=2.0.6
  - zstandard=0.18.0
  - zstd=1.5.2
  - pip:
    - attr==0.3.2
    - cachetools==4.2.4
    - click==7.1.2
    - dask==2022.7.1
    - docopt==0.6.2
    - flask==2.0.3
    - future-annotations==1.0.0
    - gdptools==0.0.13.dev0
    - geopandas==0.10.2
    - google-api-python-client==2.54.0
    - google-auth==1.35.0
    - google-auth-httplib2==0.1.0
    - h11==0.12.0
    - h5pyd==0.10.1
    - httpcore==0.15.0
    - httplib2==0.20.4
    - httpx==0.23.0
    - kbatch==0.4.1
    - kubernetes==24.2.0
    - msrestazure==0.6.4
    - noaa-coops==0.1.9
    - pydap==3.2.2
    - pygeoapi==0.11.0
    - python-dateutil==2.8.2
    - rasterstats==0.16.0
    - requests-file==1.5.1
    - requests-toolbelt==0.9.1
    - requests-unixsocket==0.3.0
    - rfc3986==1.5.0
    - simplejson==3.17.6
    - tinydb==4.7.0
    - tokenize-rt==4.2.1
    - unicodecsv==0.14.1
    - uritemplate==4.1.1
    - webob==1.8.7
    - werkzeug==2.2.0
    - xstac==1.1.0
    - zeep==4.1.0
    - git+https://github.com/fsspec/kerchunk.git
